highlighter: "rouge"
# - markdown: "kramdown"

defaults:
    -
        scope:
            path: "" # empty string for all files
            type: pages
        values:
            layout: default
    -
        scope:
            path: "" # empty string for all files
            type: posts
        values:
            layout: post

plugins:
  - jekyll-sitemap

title: "Roel Willems"
tagline: ""
description: "Follow <a href=\"https://micro.blog/roelwillems\">@roelwillems on Micro.blog</a>."
credits: "Follow <a href=\"https://micro.blog/roelwillems\">@roelwillems on Micro.blog</a>."
baseurl: ""
url: "https://roelwillems.com"
markdown: "kramdown"
username: "roelwillems"
microblog_user: "roelwillems"
permalink: "/:year/:month/:day/:title.html"
relative_permalinks: false
author: "Roel Willems"
name: "Roel Willems"
gravatar_hash: "18011d3a05eb4f299c7cdaeecc25ee72"
avatar: "https://micro.blog/roelwillems/avatar.jpg"
full_name: "Roel Willems"
bio: ""
twitter_username: ""
github_username: ""
instagram_username: ""
paginate: 20
paginate_path: "/page/:num/"
timezone: "Poland"
site_id: "940"
gems: ["jekyll-paginate"]
itunes_description: "Adsum,

living in The Netherlands, working for Albert Heijn Online (part of Ahold Delhaize). Here you will find posts on technology, personal development, data &amp; online privacy and other topics which spark my interest."
itunes_category: "Society & Culture"
itunes_subcategory: "Personal Journals"
itunes_author: "Roel Willems"
itunes_email: ""
podcast: false